apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollify-db
spec:
  selector:
    matchLabels:
      app: pollify-db
  template:
    metadata:
      labels:
        app: pollify-db
    spec:
      containers:
        - name: postgres
          image: pollify-db:latest
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pollify-db
spec:
  selector:
    app: pollify-db
  ports:
    - port: 5432
  clusterIP: None  # Headless service for stateful DB access (optional)
