FROM alpine:latest

RUN apk add --no-cache bash gcc musl-dev make readline-dev zlib-dev openssl-dev curl

# Postgres version
ENV PG_VERSION=15.2
ENV PG_SOURCE=https://ftp.postgresql.org/pub/source/v${PG_VERSION}/postgresql-${PG_VERSION}.tar.bz2

RUN curl -L -o /tmp/postgresql.tar.bz2 $PG_SOURCE \
    && mkdir /usr/src/postgres \
    && tar -xjf /tmp/postgresql.tar.bz2 -C /usr/src/postgres --strip-components=1 \
    && rm /tmp/postgresql.tar.bz2

# Install Postgres
WORKDIR /usr/src/postgres
RUN ./configure --prefix=/usr/local/pgsql \
    && make \
    && make install

RUN adduser -D postgres
RUN mkdir -p /usr/local/pgsql/data && chown -R postgres:postgres /usr/local/pgsql

USER postgres

RUN /usr/local/pgsql/bin/initdb -D /usr/local/pgsql/data

# Postgres port
EXPOSE 5432

# Start Postgres server
CMD ["/usr/local/pgsql/bin/postgres", "-D", "/usr/local/pgsql/data"]
