FROM alpine:latest

RUN apk add --no-cache bash curl tar

# Java 21
ENV JAVA_VERSION=21.0.2
ENV JAVA_BUILD=9
ENV JAVA_PACKAGE=OpenJDK21U-jdk_x64_alpine_linux_hotspot_${JAVA_VERSION}_${JAVA_BUILD}.tar.gz

RUN curl -L -o /tmp/${JAVA_PACKAGE} https://github.com/adoptium/temurin21-binaries/releases/download/jdk-${JAVA_VERSION}%2B${JAVA_BUILD}/${JAVA_PACKAGE} \
    && mkdir /opt/java \
    && tar -xzf /tmp/${JAVA_PACKAGE} -C /opt/java --strip-components=1 \
    && rm /tmp/${JAVA_PACKAGE}

#ENV variables
ENV JAVA_HOME=/opt/java
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN java -version

WORKDIR /app
COPY target/pollify-0.0.1-SNAPSHOT.jar app.jar

#springboot
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
